### ISSUE TITLE
problem connection [hbase-client] zookeeper watch error: Exception: NO_NODE[-101]

### ISSUE THREAD

**Issue by fadaytak** [alibaba/node-hbase-client#72]
hi

my config :

hadoop 2.5
hbase : 0.96
zookeeper : 3.4.6

always i have the same problem 

[Thu Sep 11 2014 18:11:36 GMT+0200 (CEST)] [worker:19663] [hbase-client] zookeeper watch error: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (/root/apps/node-hbase/node_modules/hbase-client/node_modules/zookeeper-watcher/node_modules/node-zookeeper-client/lib/ConnectionManager.js:570:35)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)

nodefile :

var HBase = require('hbase-client');
var config = {
zookeeperHosts: [
'localhost:2181',
],
zookeeperRoot: '/zookeeper',
};

var client = HBase.create(config);

client.getRow('test', 'row1', ['cf:a'], function (err, row) {
console.log("row");
  console.log(row);
console.log("err");
console.log(err);
});

any idea ? thanks

**Comment by simonchan2013** [comment]
hi, i hvae the same problem, and my hbase version is 0.94.16, have you solve it? how do you fix it? thanks

**Comment by coolme200** [comment]
Can you provide more information to reproduce the problem it is convenient for me？

**Comment by simonchan2013** [comment]
the output is:
[Wed Mar 11 2015 17:04:19 GMT+0800 (中国标准时间)] [worker:3620] [hbase-client] zookeeper watch error: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (E:\work\workspace_js\nodejs_test\node_modules\hbase-client\node_modules\zookeeper-watcher\node_modules\node-zookeeper-client\lib\ConnectionManager.js:570:35)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
{ [NO_NODE: Exception: NO_NODE[-101]]
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }
undefined


and my test program is:
var hbase = require('hbase-client');

var client = hbase.create({
	zookeeperHosts: [
		'192.168.86.15:2181',
	],
	zookeeperRoot: "/data/hbase/zookeeper_data_09416"
});

// console.log(client);

var param = new hbase.Get('row1');
param.addColumn('cf', 'a');

// console.log(param);

client.get('test', param, function(err, row) {
	console.log(err);
	console.log(row);
});

**Comment by saintybalboa** [comment]
I had a similar problem, after analyzing the Hbase log I foudn the following message:

> not start ZK at requested port of 2181.  ZK was started at port: 2182.

I specified an incorrect port number, once I changed it from **2181** to **2182** it resolved the issue.

`var client = hbase.create({
                       zookeeperHosts: [
                            '0.0.0.0:2182',
                       ],
                       zookeeperRoot: "HBASE_ROOT_DIRECTORY`,
                    });
`
